### ISSUE TITLE
Log replies not working 

### ISSUE THREAD

**Issue by iTerminate** [Olog/phoebus-olog-web-client#116]
# Problem
I just deployed the latest development branch of Olog. Everything seemed to work fine including Reply however after a little bit of use, the replies stopped working and the browser is throwing the javascript error below. I also tried to restart the service but I still get the error.

Reverting to v1.1.8 does resolve the issue. 

# Javascript Error 
```
Description.js:47 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at Object.maxRequestSize (Description.js:47:47)
    at validateField.ts:251:26
    at d (regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (regeneratorRuntime.js:133:17)
    at Generator.next (regeneratorRuntime.js:74:21)
    at zr (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:12
```

**Comment by cjenkscybercom** [comment]
Sorry about that, I've replicated and will push a fix with https://github.com/Olog/phoebus-olog-web-client/pull/119
